initial commit
jayvanpariya1679/Bootstrap-Training pull request #1
Opened 2024-01-29 06:39 UTC by jayvanpariya1679

2024-01-29 10:27 UTC, dix1999 requested changes

2024-01-29 10:27 UTC, dix1999 commented on src/main/webapp/index.html
> +            	<a href="#flag" style="margin-right: 0.75rem"><i class="fa-regular fa-flag" style="color: #ffffff"></i></a>
Don't add direct style. Use class insted at everywhere. Like below.

.white-color {
    color: #ffffff
}

2024-01-29 10:27 UTC, dix1999 commented on src/main/webapp/index.html
> +                    <div class="border bg-white"> <img alt="CPU TRAFFIC" src="images/trolly.svg" style="width: 6.25rem; height: 6.25rem;"> SALES 760 </div>
Don't add direct style. Create class insted and use it at everywhere.

2024-01-29 10:27 UTC, dix1999 commented on src/main/webapp/index.html
> +                                <div class="col-3"> <img class="direct-chat-img rounded-circle" style="width: 5rem; height: 5rem" src="images/Norman.svg" alt="message user image">
You have added a path of images but have not committed that.

2024-01-29 10:27 UTC, dix1999 commented on src/main/webapp/index.html
> +        var menuBtn = document.querySelector("#menu-btn")
Why we need script to open and close side bar. Just remove it and use bootstrap insted.

2024-01-29 10:27 UTC, dix1999 commented on src/main/webapp/style.css
> +    background-color: #fff;
Create variable for color and use it here.

2024-01-29 10:27 UTC, dix1999 commented on src/main/webapp/style.css
> +    box-shadow: 0 0 0 0.15625rem #7952b344;
Create variable for color and use it here.

2024-02-02 09:21 UTC, dix1999 requested changes

2024-02-02 09:21 UTC, dix1999 commented on src/main/webapp/CSS/style.css
> +  --dropdown-gray: #6c757d;
Let me give you an example. How to give color variable names. 

If we have variants of blue color then we can write like below.

    --blue: blue;
    --blue-primary: rgb(46 90 172);
    --blue-primary-1: rgb(0, 103, 177);
    --blue-light: rgb(238 242 250);

2024-02-02 09:21 UTC, dix1999 commented on src/main/webapp/CSS/style.css
> +    background-color: #3B71CA;
Add color to variable.

2024-02-02 09:21 UTC, dix1999 commented on src/main/webapp/index.html
> +                                <div class="progress bg-secondary mt-2 mb-2" style="height: 0.2rem;">
Remove style from everywhere and create a custom class and use it.

2024-02-02 09:25 UTC, jayvanpariya1679 commented on src/main/webapp/index.html
> +                                <div class="progress bg-secondary mt-2 mb-2" style="height: 0.2rem;">
progress bar can't support style with class

2024-02-02 13:20 UTC, dix1999 approved these changes

2024-02-02 13:20 UTC, merged